from datetime import datetime

from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.database import SessionLocal
from app.models.attendance import AttendanceRecord
from app.models.lesson import Lesson, LessonStudent
from app.services.hour_service import HourService


def run_absence_job(db: Session | None = None, now: datetime | None = None) -> int:
    """Generate absent attendance records after check-in windows close."""
    owns_session = db is None
    session = db or SessionLocal()
    current_time = now or datetime.now()
    created_count = 0

    try:
        rows = session.execute(
            select(Lesson, LessonStudent)
            .join(LessonStudent, LessonStudent.lesson_id == Lesson.id)
            .where(
                Lesson.status != "cancelled",
                Lesson.checkin_end_time < current_time,
                LessonStudent.attendance_status == "pending",
            )
        ).all()
        hours = HourService(session)
        for lesson, lesson_student in rows:
            existing = session.scalar(
                select(AttendanceRecord).where(
                    AttendanceRecord.lesson_id == lesson.id,
                    AttendanceRecord.student_id == lesson_student.student_id,
                )
            )
            if existing:
                continue

            attendance = AttendanceRecord(
                campus_id=lesson.campus_id,
                lesson_id=lesson.id,
                student_id=lesson_student.student_id,
                attendance_status="absent",
                source="system",
                note="Generated by absence job",
            )
            session.add(attendance)
            session.flush()

            lesson_student.attendance_status = "absent"
            action = hours.resolve_deduction_action(lesson=lesson, attendance_status="absent")
            if action == "deduct":
                try:
                    hours.apply_deduction(
                        attendance_record_id=attendance.id,
                        operator_user_id=None,
                        source="system",
                        reason="Absent auto deduction",
                    )
                    lesson_student.deduction_status = "deducted"
                    lesson_student.deducted_hours = lesson.default_hour_cost
                except HTTPException as exc:
                    if exc.status_code != status.HTTP_409_CONFLICT:
                        raise
                    lesson_student.deduction_status = "manual_required"
            elif action == "not_deduct":
                lesson_student.deduction_status = "not_deducted"
            else:
                lesson_student.deduction_status = "manual_required"

            created_count += 1

        if owns_session:
            session.commit()
        return created_count
    except Exception:
        if owns_session:
            session.rollback()
        raise
    finally:
        if owns_session:
            session.close()
